args = [
  "-nographic",
  "-cpu",
  "cortex-a72",
  "-machine",
  "virt,virtualization=on,gic-version=3",
  "-smp",
  "4",
  "-m",
  "8g",
]
fail_regex = [
  "(?i)\\bpanic(?:ked)?\\b",
  "(?m)^AXVISOR_AARCH64_VPCI_ENUMERATION_FAILED(?:\\s|$)",
]
success_regex = [
  "(?m)^AXVISOR_AARCH64_VPCI_ENUMERATION_PASSED\\s*$",
]
timeout = 240
to_bin = true
uefi = false
