features = []
log = "Info"
target = "aarch64-unknown-none-softfloat"
vm_configs = [
  "test-suit/axvisor/normal/qemu-ivshmem-pci-peers/configs/linux-ivshmem-peer0.toml",
  "test-suit/axvisor/normal/qemu-ivshmem-pci-peers/configs/linux-ivshmem-peer1.toml",
]

[env]
AXVISOR_TEST_BUSYBOX_INITRAMFS = "tmp/axbuild/axvisor/qemu-ivshmem-pci-peers/initramfs-aarch64.cpio.gz"
AXVISOR_TEST_ROOTFS_IMAGE = "rootfs-aarch64-alpine-ivc-message-v1.img"
AXVISOR_TEST_IVSHMEM_SMOKE = "1"
